Offer:
    resource: "@AppBundle/Resources/config/routing/routing.yml"
    prefix:   /

api:
    resource: "."
    type:     "api"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   "/doc"
